development:
  cloud_name: mckshreder
  api_key: '533784485985626'
  api_secret: 3N0_y_dnT-rzjWkGYGYYnHcuQnU
  enhance_image_tag: true
  static_image_support: false
production:
  cloud_name: mckshreder
  api_key: '533784485985626'
  api_secret: 3N0_y_dnT-rzjWkGYGYYnHcuQnU
  enhance_image_tag: true
  static_image_support: true
test:
  cloud_name: mckshreder
  api_key: '533784485985626'
  api_secret: 3N0_y_dnT-rzjWkGYGYYnHcuQnU
  enhance_image_tag: true
  static_image_support: false
